### ISSUE TITLE
(2) Onderzoek doen naar WebRTC

### ISSUE THREAD

**Issue by ath1s** [ath1s/Stully#17]
Het bekijken van de documentatie en online tutorials over WebRTC.

**Comment by MitchellvdKlij** [comment]
Ik heb een prototype gemaakt van een WebRTC call. In theorie is het mogelijk om te maken. Wat we nodig hebben is een Signalling Server, een STUN Server, en de client dan. Wel denk ik dat het veel lastiger gaat worden dan we denken en ik denk dat we alle leden nodig hebben om hieraan te werken.

**Comment by ath1s** [comment]
Vrijdag 16 april gaan we het behandelen tijdens de standup @MitchellvdKlij .
