### ISSUE TITLE
(2) Eerste concept database ontwerp maken

### ISSUE THREAD

**Issue by ath1s** [ath1s/Stully#2]

**Comment by LeviOS31** [comment]
eerst denken wat er allemaal in de database moet komen, daarna de database ontwerpen in vertabelo en daarna overzetten in sql script om hem werkent te maken

**Comment by LeviOS31** [comment]
database gemaakt en goedgekeurd

**Comment by Yuichi135** [comment]
Database nog niet compleet, er is nergens auto increment gebruikt

**Comment by ath1s** [comment]
@LeviOS31 Wat is de status op dit moment met betrekking tot dit item?

**Comment by LeviOS31** [comment]
database is af heb auto increment toegevoegt

**Comment by ath1s** [comment]
@LeviOS31 In welke commit kan ik dit terug zien?

**Comment by ath1s** [comment]
#20 completed this item.
